// Central icon registry for the ui/ component library.
// Components take an icon as a kebab-case string prop (matching the design
// system's contract); we resolve it against a curated, explicit import list
// here instead of `import * as icons from "lucide-vue-next"` everywhere,
// which would pull the entire icon set into the bundle and defeat tree-shaking.
// ponytail: fixed list, extend it when a view needs an icon not here yet.
import {
  Home,
  Users,
  Settings,
  Bookmark,
  MapPin,
  CalendarDays,
  CalendarClock,
  CalendarCheck2,
  CalendarCog,
  Calendar1,
  CalendarX,
  Hash,
  Mail,
  Activity,
  Pencil,
  Clock,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Check,
  CheckCircle,
  CheckCircle2,
  X,
  XCircle,
  Search,
  Menu,
  LogOut,
  Sun,
  Moon,
  Languages,
  AlertTriangle,
  AlertCircle,
  Image,
  FileText,
  ClipboardList,
  List,
  BarChart,
  Circle,
  User,
  UserPlus,
  UserCheck,
  UserMinus,
  UserCog,
  Plus,
  Trash2,
  Eye,
  EyeOff,
  Shield,
  Lock,
  Loader2,
  ShieldCheck,
  ShieldAlert,
  Info,
  Save,
  Palette,
  Undo2,
  Map,
  UploadCloud,
  Timer,
  AppWindow,
  Globe,
} from "lucide-vue-next";

const REGISTRY = {
  home: Home,
  users: Users,
  settings: Settings,
  bookmark: Bookmark,
  "map-pin": MapPin,
  "calendar-days": CalendarDays,
  "calendar-clock": CalendarClock,
  "calendar-check-2": CalendarCheck2,
  "calendar-cog": CalendarCog,
  "calendar-1": Calendar1,
  "calendar-x": CalendarX,
  hash: Hash,
  mail: Mail,
  activity: Activity,
  pencil: Pencil,
  clock: Clock,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  x: X,
  "x-circle": XCircle,
  search: Search,
  menu: Menu,
  "log-out": LogOut,
  sun: Sun,
  moon: Moon,
  languages: Languages,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  image: Image,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  list: List,
  "bar-chart": BarChart,
  circle: Circle,
  user: User,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-cog": UserCog,
  plus: Plus,
  trash: Trash2,
  eye: Eye,
  "eye-off": EyeOff,
  shield: Shield,
  lock: Lock,
  "loader-2": Loader2,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  info: Info,
  save: Save,
  palette: Palette,
  "undo-2": Undo2,
  map: Map,
  "upload-cloud": UploadCloud,
  timer: Timer,
  "app-window": AppWindow,
  globe: Globe,
};

/** Resolve a kebab-case Lucide icon name to its component, or null if unknown/absent. */
export function resolveIcon(name) {
  if (!name) return null;
  return REGISTRY[name] ?? null;
}
