name: Docker Builds

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-liberteis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag name
        id: extract_tag_name
        run: echo "::set-output name=tag_name::$(echo ${GITHUB_REF#refs/*/})"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Metadata
        id: meta_liberteis
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/alexdeveloperuwu/liberteis
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_liberteis.outputs.tags }}
          labels: ${{ steps.meta_liberteis.outputs.labels }}
          platforms: linux/amd64,linux/arm*
