name: Docker Builds

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-liberteis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_liberteis
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/alexdeveloperuwu/liberteis
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}-{{arch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_liberteis.outputs.tags }}
          labels: ${{ steps.meta_liberteis.outputs.labels }}
