name: Docker Builds

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-liberteis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag version
        id: extract_tag_version
        run: echo ::set-output name=tag_version::$(echo "${{ github.ref }}" | sed 's/v\(.*\)/\1/')

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/alexdeveloperuwu/liberteis:v${{ steps.extract_tag_version.outputs.tag_version }}-amd64

      - name: Build and push ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/alexdeveloperuwu/liberteis:v${{ steps.extract_tag_version.outputs.tag_version }}-arm64
