name: Docker Publish to Github Container Registry

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish-liberteis-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push Docker image
        run: |
          ARCH=$(uname -m)
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/alexdeveloperuwu/liberteis:${{ steps.extract_version.outputs.VERSION }}-$ARCH --push .